services:
  backend:
    build: backend
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    volumes:
      - ./backend/api:/var/www/html/api
    environment:
      JWT_KEY: 7fDz1Ab+74c3uG9jyZH7SSudPm0VumyrBJ+qC2iSNdE=
      MODE_DEPLOY: development
      MYSQL_HOST: database
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: password1234
    command: ["apache2-foreground"]

  database:
    build: database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=password1234"
      - "MYSQL_ROOT_PASSWORD=password1234"
      - "MYSQL_RANDOM_ROOT_PASSWORD="

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - database
    ports:
      - "8881:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password1234

volumes:
  mysql:
