ALTER TABLE Events
ADD COLUMN expired BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE Events
SET
  expired = TRUE,
  shortId = nanoid(10, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890')
WHERE shortId IS NULL;

ALTER TABLE Events
ALTER COLUMN shortId SET NOT NULL;
